//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMLAKLAR
    {
        public int ID { get; set; }
        public string ILAN_TARIHI { get; set; }
        public string ILAN_KATEGORISI { get; set; }
        public string ILAN_BASLIGI { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public string KONUT_TIPI { get; set; }
        public Nullable<int> BINA_YASI { get; set; }
        public string ISINMA_TIPI { get; set; }
        public Nullable<int> ODA_SAYISI { get; set; }
        public Nullable<int> SALON_SAYISI { get; set; }
        public Nullable<int> BANYO_SAYISI { get; set; }
        public Nullable<int> BURUT_METREKARE { get; set; }
        public Nullable<int> NET_METREKARE { get; set; }
        public Nullable<int> KAT_SAYISI { get; set; }
        public string BULUNDUGU_KAT { get; set; }
        public string KULLANIM_DURUMU { get; set; }
        public Nullable<int> AIDAT { get; set; }
        public Nullable<int> IL_ID { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
    
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual ILLER ILLER { get; set; }
    }
}
