//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILLER()
        {
            this.ILCELER = new HashSet<ILCELER>();
            this.EMLAKLAR = new HashSet<EMLAKLAR>();
        }
    
        public int ID { get; set; }
        public string ILADI { get; set; }
        public string ALANKODU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILCELER> ILCELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMLAKLAR> EMLAKLAR { get; set; }
    }
}
