//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERILER()
        {
            this.EMLAKLAR = new HashSet<EMLAKLAR>();
        }
    
        public int ID { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string EMAIL { get; set; }
        public string SIFRE { get; set; }
        public string EVTEL { get; set; }
        public string CEPTEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMLAKLAR> EMLAKLAR { get; set; }
    }
}
